### PR TITLE
Prettifying code

### PR DESCRIPTION
**Pull request by bvanrijn**
Hi,

On a related note, is the excessive usage of newlines in TextSuggest.py intentional?
See for instance [here](https://github.com/bharadwaj-raju/TextSuggest/blob/master/TextSuggest.py#L97:L115). I would personally have written this as

```
def restart_program(additional_args=[], remove_args=[]):
    # Restart, preserving all original arguments and optionally adding more
    new_cmd = ''

    for i in sys.argv:
        new_cmd += ' ' + i

    if not remove_args == []:
        for arg in remove_args:
            if arg in new_cmd:
                new_cmd = new_cmd.replace(arg, '')
```

I look forward to hearing from you,
Barend

### CODE REVIEW

**Comment by bharadwaj-raju** [comment]
Is that conversion of tabs to spaces? I know [PEP says spaces](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces), but tabs are good because they can be adjusted in each developer's editor.

**Comment by bharadwaj-raju** [comment]
As for the large amount of empty lines: I'm just used to doing that, and I'm probably overdoing it. :)

**Comment by bvanrijn** [comment]
I can sit down and establish both an [.editorconfig](http://editorconfig.org/) file and remove the unnecessary new lines.

**Comment by bvanrijn** [comment]
Accidentally closed

**Comment by bharadwaj-raju** [comment]
Sorry, but
1. Newlines have now been removed
2. We are sticking to tabs

Still, thank you!

**Pull request closed without merging**
