### PR TITLE
Changing directory tree

### PR DESCRIPTION
**Pull request by maateen**

### CODE REVIEW

**Comment by maateen** [comment]
@bharadwaj-raju  Please consider these changes.

**Comment by bharadwaj-raju** [comment]
@maateen I'm sorry, but I've done these changes myself, just have to commit.

**Comment by maateen** [comment]
OKay. :+1: Push commit. Then I will read and merge and request pull again.

**Comment by bharadwaj-raju** [comment]
I've committed changes myself, closing.

**Pull request closed without merging**
