### PR TITLE
Making more efficient

### PR DESCRIPTION
**Pull request by maateen**
1. Restructuring
2. Fixing a bug in `languages.py`
3. Re-adding `fonts.py`
4. Removing unnecessary `is not None` statement

### CODE REVIEW

**Comment by bharadwaj-raju** [comment]
The `.strip()` was added because some keyboard codes are three-characters in length, and all of them include an extra newline at the end.

Also, we should include the Bangla dictionary when it's complete -- three words aren't a complete dictionary :smile:.

Note to self: Update deb, update README manual install instructions, tell shellkr to update AUR package.

**Comment by bharadwaj-raju** [comment]
I left the `custom_words_file` in `~/.Custom_Words.txt` because of ... backward compatibility -- an update would break the custom dictionaries of all users.

Maybe we should silently move `~/.Custom_Words.txt` (if found) to its new location, and create a symlink.

**Comment by bharadwaj-raju** [comment]
@maateen ^

**Comment by maateen** [comment]
I am implementing it. Please wait a little bit.

**Comment by maateen** [comment]
> The .strip() was added because some keyboard codes are three-characters in length, and all of them include an extra newline at the end.

We have to do an exception. But most of the layouts work with 1st two chars.

> Also, we should include the Bangla dictionary when it's complete -- three words aren't a complete dictionary

Doing it. :cry: I need more time. Added those words, just for testing.

> Maybe we should silently move ~/.Custom_Words.txt (if found) to its new location, and create a symlink.

OKay, This has been implemented. :smile: You can merge now.

**Pull request merged**
