### PR TITLE
Silently moved ~/.Custom_Words.txt (if found) to its new location

### PR DESCRIPTION
**Pull request by maateen**
Silently moved `~/.Custom_Words.txt` (if found) to its new location

### CODE REVIEW

**Comment by maateen** [comment]
@bharadwaj-raju  Sorry to bother you again. :cry: `Silently moved ~/.Custom_Words.txt (if found) to its new location` unfortunately was not committed then.

**Comment by bharadwaj-raju** [comment]
One thing: I learned that most default fonts: nearly all Monospace fonts, Ubuntu's default set, GNOME's Cantarell include nearly _every_ character in UTF-8, and most distros/desktop environments set Noto Sans as a fallback font if UTF-8 character is not supported by current font.

So we can just remove the language-fonts system entirely.

**Comment by maateen** [comment]
> So we can just remove the language-fonts system entirely.

No you can't at all. You may notice that I have connected to this project as I want to make this available in my language **Bangla**. That's my main target. 

By default, Ubuntu-16.04 LTS doesn't come with **Bangla** font anymore. In previous, it shipped with some Bangla fonts like **Kalpurush**, **Lohit Bangla** etc. But after that we need **SolaimanLipi**, **Siyam Rupali** to get a breaking free font.

So, from my view, we shouldn't remove them.

**Comment by bharadwaj-raju** [comment]
Okay, then :)

**Comment by bharadwaj-raju** [comment]
Can you post the output of:

```
setxkbmap -print | awk -F"+" '/xkb_symbols/ {print $2}'
```

**Pull request merged**
