### PR TITLE
Fixing AttributeError: 'NoneType' object has no attribute 'decode'

### PR DESCRIPTION
**Pull request by maateen**
```
Traceback (most recent call last):
  File "TextSuggest.py", line 276, in <module>
    apply_suggestion(display_dialog_list(get_suggestions(current_word)))
  File "TextSuggest.py", line 208, in apply_suggestion
    suggestion = suggestion.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

It's just a fix of this issue.

### CODE REVIEW

**Comment by bharadwaj-raju** [comment]
Changing the variable name won't fix errors. _sigh_ Please look at Installation again.

**Comment by maateen** [comment]
Sorry @bharadwaj-raju. It was a mistake, that's why I have closed the pull request. Please don't be bother. 

By the way, installation is okay. But this script has some bugs. I have started to fix them along with bringing Bengali support.

**Comment by bharadwaj-raju** [comment]
Bugs? Please report them in issues.

**Comment by bharadwaj-raju** [comment]
Also, see https://github.com/bharadwaj-raju/TextSuggest/issues/2#issuecomment-227831950.

**Pull request closed without merging**
